/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Entidades.Player;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author AgusGonza
 */
public class CreateUser extends javax.swing.JFrame {

    /**
     * Creates new form CreateUser
     */
    public CreateUser() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        TUserName = new javax.swing.JLabel();
        TxtUserName = new javax.swing.JTextField();
        separatorUser = new javax.swing.JSeparator();
        TPassword = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JPasswordField();
        separatorPass = new javax.swing.JSeparator();
        TPassword2 = new javax.swing.JLabel();
        TxtPassword2 = new javax.swing.JPasswordField();
        separatorPass1 = new javax.swing.JSeparator();
        BtnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(0, 0, 0));
        Title.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 26)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setText("Create User");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        TUserName.setBackground(new java.awt.Color(0, 0, 0));
        TUserName.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        TUserName.setForeground(new java.awt.Color(0, 0, 0));
        TUserName.setText("User Name ");
        jPanel1.add(TUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        TxtUserName.setBackground(new java.awt.Color(255, 255, 255));
        TxtUserName.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        TxtUserName.setForeground(new java.awt.Color(0, 0, 0));
        TxtUserName.setBorder(null);
        TxtUserName.setCaretColor(new java.awt.Color(153, 153, 153));
        TxtUserName.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.add(TxtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, 20));

        separatorUser.setBackground(new java.awt.Color(0, 0, 0));
        separatorUser.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(separatorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, 20));

        TPassword.setBackground(new java.awt.Color(0, 0, 0));
        TPassword.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        TPassword.setForeground(new java.awt.Color(0, 0, 0));
        TPassword.setText("Password");
        jPanel1.add(TPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        TxtPassword.setBackground(new java.awt.Color(255, 255, 255));
        TxtPassword.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        TxtPassword.setForeground(new java.awt.Color(0, 0, 0));
        TxtPassword.setBorder(null);
        jPanel1.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 160, 20));

        separatorPass.setBackground(new java.awt.Color(0, 0, 0));
        separatorPass.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(separatorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 160, 20));

        TPassword2.setBackground(new java.awt.Color(0, 0, 0));
        TPassword2.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        TPassword2.setForeground(new java.awt.Color(0, 0, 0));
        TPassword2.setText("Repeat password");
        jPanel1.add(TPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        TxtPassword2.setBackground(new java.awt.Color(255, 255, 255));
        TxtPassword2.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        TxtPassword2.setForeground(new java.awt.Color(0, 0, 0));
        TxtPassword2.setBorder(null);
        jPanel1.add(TxtPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, 20));

        separatorPass1.setBackground(new java.awt.Color(0, 0, 0));
        separatorPass1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(separatorPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 20));

        BtnRegister.setBackground(new java.awt.Color(255, 255, 255));
        BtnRegister.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        BtnRegister.setForeground(new java.awt.Color(0, 0, 0));
        BtnRegister.setText("Register");
        BtnRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnRegister.setContentAreaFilled(false);
        BtnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegister.setFocusPainted(false);
        BtnRegister.setFocusable(false);
        BtnRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRegister.setOpaque(true);
        BtnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnRegisterMouseExited(evt);
            }
        });
        jPanel1.add(BtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 110, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkUser(String userName){
        
        List <Player> listPlayer = Player.getListPlayer();
        
        for (Player aux : listPlayer){
            
            if (aux.getUserName().equals(userName)){
                
                return true;
            }
        }
        
        
        return false;
    }
    private void BtnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegisterMouseEntered
        BtnRegister.setBackground (new Color (153,0,0));
        BtnRegister.setForeground(new Color (255,204,51));
    }//GEN-LAST:event_BtnRegisterMouseEntered

    private void BtnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegisterMouseExited
        BtnRegister.setBackground(Color.WHITE);
        BtnRegister.setForeground(new Color (0,0,0));
    }//GEN-LAST:event_BtnRegisterMouseExited
        
    private void BtnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegisterMouseClicked
        
        if ( !checkUser(TxtUserName.getText())){
            
             if (TxtPassword.getText().equals(TxtPassword2.getText())){
            
                Player.createPlayer(TxtUserName.getText(), TxtPassword.getText());
                JOptionPane.showMessageDialog(null, "Player created successfully");
            
            }else{
                 
                JOptionPane.showMessageDialog(null, "Passwords do not match");
            }
            
        }else{
            
            JOptionPane.showMessageDialog(null, "User already exists");
        }
        
       
    }//GEN-LAST:event_BtnRegisterMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegister;
    private javax.swing.JLabel TPassword;
    private javax.swing.JLabel TPassword2;
    private javax.swing.JLabel TUserName;
    private static javax.swing.JLabel Title;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JPasswordField TxtPassword2;
    private javax.swing.JTextField TxtUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator separatorPass;
    private javax.swing.JSeparator separatorPass1;
    private javax.swing.JSeparator separatorUser;
    // End of variables declaration//GEN-END:variables
}
