/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Entidades.Player;
import java.awt.Color;
import javax.swing.JOptionPane;
import main.Main;

/**
 *
 * @author Juanjo y Agus
 */
public class MainMenu extends javax.swing.JFrame {

    private static Player actualUser = null;
    
    public static void setActualUser(Player actualUser){
        
        MainMenu.actualUser = actualUser;
        ActualUserTxt.setText("Usuario actual: " + actualUser.getUserName());
        Player.loadPlayer(actualUser);
        TxtCoins.setText(actualUser.getCoins().toString());
        initStats();
        initShopCars();
       
        
    }
    
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lPassword = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Drift = new javax.swing.JLabel();
        displayUsername4 = new javax.swing.JLabel();
        MaximunLife = new javax.swing.JLabel();
        ActualUserTxt = new javax.swing.JLabel();
        TxtCoins = new javax.swing.JLabel();
        BtnPlay = new javax.swing.JButton();
        displayUsername5 = new javax.swing.JLabel();
        DriftProgress = new javax.swing.JProgressBar();
        LifeProgress = new javax.swing.JProgressBar();
        AFProgress = new javax.swing.JProgressBar();
        BtnAddDriff = new javax.swing.JLabel();
        BtnAddLife = new javax.swing.JLabel();
        BtnAddAF = new javax.swing.JLabel();
        DriftCost = new javax.swing.JLabel();
        LifeCost = new javax.swing.JLabel();
        AFCost = new javax.swing.JLabel();
        displayUsername6 = new javax.swing.JLabel();
        AutoDefault = new javax.swing.JLabel();
        AutoTurro = new javax.swing.JLabel();
        AutoBussines = new javax.swing.JLabel();
        AutoPolicia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lPassword.setBackground(new java.awt.Color(0, 0, 0));
        lPassword.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 26)); // NOI18N
        lPassword.setForeground(new java.awt.Color(0, 0, 0));
        lPassword.setText("Selected Car");
        jPanel1.add(lPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, 10));

        Drift.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 18)); // NOI18N
        Drift.setForeground(new java.awt.Color(0, 0, 0));
        Drift.setText("Drift");
        jPanel1.add(Drift, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 170, -1));

        displayUsername4.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        displayUsername4.setForeground(new java.awt.Color(0, 0, 0));
        displayUsername4.setText("WorkShop:");
        jPanel1.add(displayUsername4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, -1));

        MaximunLife.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 18)); // NOI18N
        MaximunLife.setForeground(new java.awt.Color(0, 0, 0));
        MaximunLife.setText("Maximun Life");
        jPanel1.add(MaximunLife, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, -1));

        ActualUserTxt.setBackground(new java.awt.Color(0, 0, 0));
        ActualUserTxt.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 26)); // NOI18N
        ActualUserTxt.setForeground(new java.awt.Color(0, 0, 0));
        ActualUserTxt.setText("User Name");
        jPanel1.add(ActualUserTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        TxtCoins.setBackground(new java.awt.Color(0, 0, 0));
        TxtCoins.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 18)); // NOI18N
        TxtCoins.setForeground(new java.awt.Color(0, 0, 0));
        TxtCoins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coin.png"))); // NOI18N
        TxtCoins.setText("Coins");
        jPanel1.add(TxtCoins, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, -1));

        BtnPlay.setBackground(new java.awt.Color(255, 255, 255));
        BtnPlay.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 18)); // NOI18N
        BtnPlay.setForeground(new java.awt.Color(0, 0, 0));
        BtnPlay.setText("Play");
        BtnPlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnPlay.setContentAreaFilled(false);
        BtnPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPlay.setFocusPainted(false);
        BtnPlay.setFocusable(false);
        BtnPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPlay.setOpaque(true);
        BtnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnPlayMouseExited(evt);
            }
        });
        BtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlayActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 150, 50));

        displayUsername5.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 18)); // NOI18N
        displayUsername5.setForeground(new java.awt.Color(0, 0, 0));
        displayUsername5.setText("Acceleration Force");
        jPanel1.add(displayUsername5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 170, -1));
        jPanel1.add(DriftProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, 20));
        jPanel1.add(LifeProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, 20));
        jPanel1.add(AFProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, 20));

        BtnAddDriff.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BtnAddDriff.setForeground(new java.awt.Color(0, 0, 0));
        BtnAddDriff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAddDriff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addPoint.png"))); // NOI18N
        BtnAddDriff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAddDriff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAddDriff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddDriffMouseClicked(evt);
            }
        });
        jPanel1.add(BtnAddDriff, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 30, 20));

        BtnAddLife.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BtnAddLife.setForeground(new java.awt.Color(0, 0, 0));
        BtnAddLife.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAddLife.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addPoint.png"))); // NOI18N
        BtnAddLife.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAddLife.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAddLife.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddLifeMouseClicked(evt);
            }
        });
        jPanel1.add(BtnAddLife, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 30, 20));

        BtnAddAF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BtnAddAF.setForeground(new java.awt.Color(0, 0, 0));
        BtnAddAF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAddAF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addPoint.png"))); // NOI18N
        BtnAddAF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAddAF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAddAF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddAFMouseClicked(evt);
            }
        });
        jPanel1.add(BtnAddAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 30, 20));

        DriftCost.setForeground(new java.awt.Color(0, 0, 0));
        DriftCost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buyStats.png"))); // NOI18N
        DriftCost.setText("10");
        jPanel1.add(DriftCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, 20));

        LifeCost.setForeground(new java.awt.Color(0, 0, 0));
        LifeCost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buyStats.png"))); // NOI18N
        LifeCost.setText("10");
        jPanel1.add(LifeCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, 20));

        AFCost.setForeground(new java.awt.Color(0, 0, 0));
        AFCost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buyStats.png"))); // NOI18N
        AFCost.setText("10");
        jPanel1.add(AFCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, 20));

        displayUsername6.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 18)); // NOI18N
        displayUsername6.setForeground(new java.awt.Color(0, 0, 0));
        displayUsername6.setText("Model: \"Nombre del auto\"");
        jPanel1.add(displayUsername6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 270, -1));

        AutoDefault.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AutoDefault.setForeground(new java.awt.Color(0, 0, 0));
        AutoDefault.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AutoDefault.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AutoDefault.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AutoDefault.setPreferredSize(new java.awt.Dimension(160, 150));
        AutoDefault.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AutoDefaultMouseClicked(evt);
            }
        });
        jPanel1.add(AutoDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        AutoTurro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AutoTurro.setForeground(new java.awt.Color(0, 0, 0));
        AutoTurro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AutoTurro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AutoTurro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AutoTurro.setPreferredSize(new java.awt.Dimension(160, 150));
        AutoTurro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AutoTurroMouseClicked(evt);
            }
        });
        jPanel1.add(AutoTurro, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        AutoBussines.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AutoBussines.setForeground(new java.awt.Color(0, 0, 0));
        AutoBussines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AutoBussines.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AutoBussines.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AutoBussines.setPreferredSize(new java.awt.Dimension(160, 150));
        AutoBussines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AutoBussinesMouseClicked(evt);
            }
        });
        jPanel1.add(AutoBussines, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        AutoPolicia.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AutoPolicia.setForeground(new java.awt.Color(0, 0, 0));
        AutoPolicia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AutoPolicia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AutoPolicia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AutoPolicia.setPreferredSize(new java.awt.Dimension(160, 150));
        AutoPolicia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AutoPoliciaMouseClicked(evt);
            }
        });
        jPanel1.add(AutoPolicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private static void initShopCars(){
        
        Integer shopCarsValue = actualUser.getStats().getsCarsValue();
        
        System.out.println(shopCarsValue);
        
        if (shopCarsValue == 25){
            
            AutoBussines.setText("$100");
            AutoPolicia.setText("$200");
            AutoTurro.setText("$300");
            
        }else if (shopCarsValue == 50){
            
            AutoBussines.setText("");
            AutoPolicia.setText("$200");
            AutoTurro.setText("$300");
            
        }else if(shopCarsValue == 75){
            
            AutoBussines.setText("");
            AutoPolicia.setText("");
            AutoTurro.setText("$300");
            
        }else if(shopCarsValue == 100){
            
            AutoBussines.setText("");
            AutoPolicia.setText("");
            AutoTurro.setText("");
        }
    }
    private static void initStats (){
        
        Integer lifeValue = actualUser.getStats().getHealtValues();
        Integer afValue = actualUser.getStats().getForceValues();
        Integer driftValue = actualUser.getStats().getDriftValues();
        
        if (lifeValue >= 20){
            
            LifeProgress.setValue(lifeValue);
            Integer cost = (lifeValue/2 + 10);
            LifeCost.setText(cost.toString());
        }
        
        if (afValue >= 20){
            
            AFProgress.setValue(afValue);
            Integer cost = (afValue/2 + 10);
            AFCost.setText(cost.toString());
        }
            
        if (driftValue >= 20){
            
            DriftProgress.setValue(driftValue);
            Integer cost = (driftValue/2 + 10);
            DriftCost.setText(cost.toString());
        }
 
        
    }
    
    private void BtnPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPlayMouseExited
        
        BtnPlay.setBackground(Color.WHITE);
        BtnPlay.setForeground(new Color (0,0,0));
    }//GEN-LAST:event_BtnPlayMouseExited

    private void BtnPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPlayMouseEntered
        
        BtnPlay.setBackground (new Color (153,0,0));
        BtnPlay.setForeground(new Color (255,204,51));
    }//GEN-LAST:event_BtnPlayMouseEntered

    private void BtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlayActionPerformed
       
    }//GEN-LAST:event_BtnPlayActionPerformed

    private void BtnAddLifeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddLifeMouseClicked
        
        if (Integer.parseInt(TxtCoins.getText()) > LifeProgress.getValue() && LifeProgress.getValue() < 80){
            
            Integer lifeCost = Integer.parseInt(LifeCost.getText());
            LifeProgress.setValue(LifeProgress.getValue() + 20);
            actualUser.setCoins(actualUser.getCoins() - lifeCost);
            TxtCoins.setText(actualUser.getCoins().toString());
            lifeCost += 10;
            LifeCost.setText(lifeCost.toString());
            actualUser.getStats().incremetHealt();
        }
        else if (LifeProgress.getValue() == 80){
            
            Integer lifeCost = Integer.parseInt(LifeCost.getText());
            LifeProgress.setValue(LifeProgress.getValue() + 20);
            actualUser.setCoins(actualUser.getCoins() - lifeCost);
            TxtCoins.setText(actualUser.getCoins().toString());
            lifeCost += 10;
            LifeCost.setText(lifeCost.toString());
            actualUser.getStats().incremetHealt();
            
            LifeCost.setText("MAX.");
            LifeCost.setIcon(null);
            JOptionPane.showMessageDialog(null, "You already have the maximum stats");
        }
        else if (LifeProgress.getValue() == 100){
            
            JOptionPane.showMessageDialog(null, "You already have the maximum stats");
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Insufficient points");
        }
        
    }//GEN-LAST:event_BtnAddLifeMouseClicked

    private void BtnAddAFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddAFMouseClicked
       
        if (Integer.parseInt(TxtCoins.getText()) > AFProgress.getValue() && AFProgress.getValue() < 80){
            
            Integer AFCost = Integer.parseInt(this.AFCost.getText());
            AFProgress.setValue(AFProgress.getValue() + 20);
            actualUser.setCoins(actualUser.getCoins() - AFCost);
            TxtCoins.setText(actualUser.getCoins().toString());
            AFCost += 10;
            this.AFCost.setText(AFCost.toString());
            actualUser.getStats().incremetForce();
        }
        else if (AFProgress.getValue() == 80){
            
            Integer AFCost = Integer.parseInt(this.AFCost.getText());
            AFProgress.setValue(AFProgress.getValue() + 20);
            actualUser.setCoins(actualUser.getCoins() - AFCost);
            TxtCoins.setText(actualUser.getCoins().toString());
            AFCost += 10;
            this.AFCost.setText(AFCost.toString());
            actualUser.getStats().incremetForce();
                       
            this.AFCost.setText("MAX.");
            this.AFCost.setIcon(null);
            JOptionPane.showMessageDialog(null, "You already have the maximum stats");
        }
        else if (AFProgress.getValue() == 100){
            
            JOptionPane.showMessageDialog(null, "You already have the maximum stats");
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Insufficient points");
        }
        
    }//GEN-LAST:event_BtnAddAFMouseClicked

    private void BtnAddDriffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddDriffMouseClicked
        
        if (Integer.parseInt(TxtCoins.getText()) > DriftProgress.getValue() && DriftProgress.getValue() < 80){
            
            Integer driftCost = Integer.parseInt(this.DriftCost.getText());
            DriftProgress.setValue(DriftProgress.getValue() + 20);
            actualUser.setCoins(actualUser.getCoins() - driftCost);
            TxtCoins.setText(actualUser.getCoins().toString());
            driftCost += 10;
            DriftCost.setText(driftCost.toString());
            actualUser.getStats().incremetDrift();
        }
        else if (DriftProgress.getValue() == 80){
            
            Integer driftCost = Integer.parseInt(this.DriftCost.getText());
            DriftProgress.setValue(DriftProgress.getValue() + 20);
            actualUser.setCoins(actualUser.getCoins() - driftCost);
            TxtCoins.setText(actualUser.getCoins().toString());
            driftCost += 10;
            DriftCost.setText(driftCost.toString());
            actualUser.getStats().incremetDrift();
            
            DriftCost.setText("MAX.");
            DriftCost.setIcon(null);
            JOptionPane.showMessageDialog(null, "You already have the maximum stats");
        }
        else if (DriftProgress.getValue() == 100){
            
            JOptionPane.showMessageDialog(null, "You already have the maximum stats");
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Insufficient points");
        }
        
    }//GEN-LAST:event_BtnAddDriffMouseClicked

    private void BtnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPlayMouseClicked
        
        Player.savePlayer(actualUser);
        JOptionPane.showMessageDialog(null, "User saved");
        
    }//GEN-LAST:event_BtnPlayMouseClicked

    private void AutoTurroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutoTurroMouseClicked
        
        if(AutoTurro.getText().equals("Lock")){
            
            
        }
    }//GEN-LAST:event_AutoTurroMouseClicked

    private void AutoBussinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutoBussinesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoBussinesMouseClicked

    private void AutoPoliciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutoPoliciaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoPoliciaMouseClicked

    private void AutoDefaultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutoDefaultMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoDefaultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel AFCost;
    private static javax.swing.JProgressBar AFProgress;
    private static javax.swing.JLabel ActualUserTxt;
    private static javax.swing.JLabel AutoBussines;
    private static javax.swing.JLabel AutoDefault;
    private static javax.swing.JLabel AutoPolicia;
    private static javax.swing.JLabel AutoTurro;
    private javax.swing.JLabel BtnAddAF;
    private javax.swing.JLabel BtnAddDriff;
    private javax.swing.JLabel BtnAddLife;
    private javax.swing.JButton BtnPlay;
    private javax.swing.JLabel Drift;
    private static javax.swing.JLabel DriftCost;
    private static javax.swing.JProgressBar DriftProgress;
    private static javax.swing.JLabel LifeCost;
    private static javax.swing.JProgressBar LifeProgress;
    private javax.swing.JLabel MaximunLife;
    private static javax.swing.JLabel TxtCoins;
    private javax.swing.JLabel displayUsername4;
    private javax.swing.JLabel displayUsername5;
    private javax.swing.JLabel displayUsername6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lPassword;
    // End of variables declaration//GEN-END:variables
}
